on:
  push:
    tags:
    - ver-**

jobs:
  none:
    name: none
    runs-on: ubuntu-latest

    container:
      image: alt:sisyphus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
